package Exception_Handling;

public class Exception1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			int c=1/1;
			System.out.println(c);
		}
		
		
		catch (ArithmeticException   c) {
			
			System.out.println("hi");
			
		}

	}

}
